#!/bin/bash
. "/home/oli/.cache/wal/colors.sh"

normalcolor=$color15
changedcolor=$color1
highlightcolor=$color1

spotify() {
    isplaying=$(/home/oli/Src/i3spotifystatus/getInfo.sh status)
    if [[ $isplaying == "Playing" ]]; then
        artist=$(/home/oli/Src/i3spotifystatus/getInfo.sh artist)
        song=$(/home/oli/Src/i3spotifystatus/getInfo.sh song)
        echo "<span color='$normalcolor'> $artist - $song</span>"
    fi
}

brgt() {
    brgt=$(xbacklight | awk -F'.' '{ print $1 }')
    if [[ $1 == "bgrt" ]];then
        color="$changedcolor"
    else
        color="$normalcolor"
    fi
    echo "<span color='$color'>󰃟 $brgt</span>"
}

radio() {
    if [[ -f "/home/oli/Dev/bash/station" ]]; then 
        station=$(cat ~/Dev/bash/station)
        if [[ ! -z $station ]]; then
            echo "<span color='$normalcolor'>$station</span>"
        fi
    fi
}

battery() {
    status=$(cat /sys/class/power_supply/BAT0/status)
    capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    color="$normalcolor"
    case "$status" in
        "Not charging")
            status_icon="󱟢"
            ;;
        "Discharging")
            status_icon="󱟤"
            color="$highlightcolor"
            ;;
        "Charging")
            status_icon=""
            ;;
        *)
            ;;
    esac
    echo "<span color='$color'>$status_icon $capacity%</span>"
}

weather() {
    if [[ -f "/home/oli/Src/ansiweather/weather" ]]; then 
        weather=$(cat ~/Src/ansiweather/weather)
        if [[ -z $weather ]]; then
            echo "󱣶 wait"
        else
            echo $weather
        fi
    else
        echo "󱣶 wait"
    fi

}

volume_pa() {
    if [[ -f "/home/oli/Dev/bash/vol" ]]; then 
        if [[ $1 == "vol" ]];then
            color="$changedcolor"
        else
            color="$normalcolor"
        fi
        file=$(cat ~/Dev/bash/vol)
        dev=$(pactl list sinks | grep '^[[:space:]]Volume:' | tail -n 1 | head -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
        if [[ -z $dev ]];then
            echo "<span color='$color'>$file</span>"
        else
            echo "<span color='$color'>󰎄 $dev</span>"
        fi
    else
        if [[ $1 == "vol" ]];then
            color="$changedcolor"
        else
            color="$highlightcolor"
        fi
        echo "<span color='$color'>󰎄 --</span>"
    fi
}

keyboard() {

    if [[ -f "/home/oli/Dev/bash/xkb" ]]; then 
        if [[ $1 == "kbd" ]];then
            color="$changedcolor"
        else
            color="$normalcolor"
        fi
        tmp=$(cat ~/Dev/bash/xkb)
        echo "<span color='$color'>$tmp</span>"
    else
        if [[ $1 == "kbd" ]];then
            color="$changedcolor"
        else
            color="$highlightcolor"
        fi
        tmp=$(cat ~/Dev/bash/xkb)
        echo "<span color='$color'> gr</span>"
    fi
}

dayinf() {
	dte=$(date +"%d.%m")
    echo " $dte"
}

clock() {
	time=$(date +"%H:%M")
	echo "<span color='$highlightcolor'>$time</span>"
}

main() {
    xsetroot -name "$(spotify)$(radio)    $(weather)    $(dayinf)    $(brgt $1)    $(volume_pa $1)    $(keyboard $1)    $(battery)    $(clock) "
}

main $1
