#!/bin/bash

spotify() {
    isplaying=$(/home/oli/Src/i3spotifystatus/getInfo.sh status)
    if [[ $isplaying == "Playing" ]]; then
        artist=$(/home/oli/Src/i3spotifystatus/getInfo.sh artist)
        song=$(/home/oli/Src/i3spotifystatus/getInfo.sh song)
        echo "<span color='#9ec600'> $artist - $song</span>"
    fi
}

radio() {
    if [[ -f "/home/oli/Dev/bash/station" ]]; then 
        station=$(cat ~/Dev/bash/station)
        if [[ ! -z $station ]]; then
            echo "<span color='#9ec600'>$station</span>"
        fi
    fi
}

battery() {
    status=$(cat /sys/class/power_supply/BAT0/status)
    capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    color="#bbbbbb"
    case "$status" in
        "Not charging")
            status_icon="󱟢"
            ;;
        "Discharging")
            status_icon="󱟤"
            color="#83cafa"
            ;;
        "Charging")
            status_icon=" "
            ;;
        *)
            ;;
    esac
    echo "<span color='$color'>$status_icon $capacity%</span>"
}

weather() {
    if [[ -f "/home/oli/Src/ansiweather/weather" ]]; then 
        weather=$(cat ~/Src/ansiweather/weather)
        if [[ -z $weather ]]; then
            echo "󱣶 wait"
        else
            echo $weather
        fi
    else
        echo "󱣶 wait"
    fi

}

volume_pa() {
    if [[ -f "/home/oli/Dev/bash/vol" ]]; then 
        cat ~/Dev/bash/vol
    else
        echo "<span color='#83cafa'>󰎄 --</span>"
    fi
}

keyboard() {
    if [[ -f "/home/oli/Dev/bash/xkb" ]]; then 
        cat ~/Dev/bash/xkb
    else
        echo "<span color='#83cafa'> gr</span>"
    fi
}

dayinf() {
	dte=$(date +"%d.%m")
    echo " $dte"
}

clock() {
	time=$(date +"%H:%M")
	echo "<span color='#83cafa'> $time</span>"
}

main() {
    xsetroot -name "$(spotify)$(radio)    $(weather)    $(dayinf)    $(volume_pa)    $(keyboard)    $(battery)    $(clock) "
}

main
